const temas = [
    "Administração, Negócios e Economia",
    "Arte, Cinema e Fotografia",
    "Artesanato, Casa e Estilo de Vida",
    "Autoajuda",
    "Biografias e Histórias Reais",
    "Ciências",
    "Computação, Informática e Mídias Digitais",
    "Crônicas, Humor e Entretenimento",
    "Direito",
    "Erótico",
    "Esportes e Lazer",
    "Fantasia, Horror e Ficção Científica",
    "Gastronomia e Culinária",
    "HQs, Mangás e Graphic Novels",
    "História",
    "Infantil",
    "Inglês e Outras Línguas",
    "Jovens e Adolescentes",
    "LGBT",
    "Literatura e Ficção",
    "Língua, Linguística e Redação",
    "Medicina",
    "Policial, Suspense e Mistério",
    "Política",
    "Referência",
    "Religião e Espiritualidade",
    "Romance",
    "Saúde e Família",
    "Sociedade e Ciências Sociais",
    "Turismo e Viagem"
  ];
  

  const linksPorTema = [
    "https://amzn.to/3NIU1iO",
    "https://amzn.to/3LFfshO",
    "https://amzn.to/3pckx9X",
    "https://amzn.to/3I6d4Qv",
    "https://amzn.to/418npSu",
    "https://amzn.to/417o7iY",
    "https://amzn.to/3LBrvwH",
    "https://amzn.to/3HLbJ17",
    "https://amzn.to/3LX882q",
    "https://amzn.to/3M1Ixpj",
    "https://amzn.to/3NDhYrD",
    "https://amzn.to/3AZmNUE",
    "https://amzn.to/41dxDRs",
    "https://amzn.to/44wX9nA",
    "https://amzn.to/3B3tEw4",
    "https://amzn.to/3VDnOv5",
    "https://amzn.to/3pfihPn",
    "https://amzn.to/3HEFSPJ",
    ""

  ]