temas = [
    "Administração, Negócios e Economia",
    "Arte, Cinema e Fotografia",
    "Artesanato, Casa e Estilo de Vida",
    "Autoajuda",
    "Biografias e Histórias Reais",
    "Ciências",
    "Computação, Informática e Mídias Digitais",
    "Direito",
    "Erótico",
    "Esportes e Lazer",
    "Fantasia, Horror e Ficção Científica",
    "Gastronomia e Culinária",
    "HQs, Mangás e Graphic Novels",
    "História",
    "Infantil",
    "Inglês e Outras Línguas",
    "Jovens e Adolescentes",
    "LGBT",
    "Literatura e Ficção",
    "Língua, Linguística e Redação",
    "Medicina",
    "Policial, Suspense e Mistério",
    "Política",
    "Referência",
    "Religião e Espiritualidade",
    "Romance",
    "Saúde e Família",
    "Sociedade e Ciências Sociais",
    "Turismo e Viagem"
  ];
  

linksPorTema = [
    "https://amzn.to/42Q0Cg1",
    "https://amzn.to/43914Wn",
    "https://amzn.to/42QR1pb",
    "https://amzn.to/3OpTEtz",
    "https://amzn.to/3WgMREx",
    "https://amzn.to/3IqqGGg",
    "https://amzn.to/45siEXo",
    "https://amzn.to/3WgZRdm",
    "https://amzn.to/42SyicJ",
    "https://amzn.to/3NDhYrD",
    "https://amzn.to/3pN1ljc",
    "https://amzn.to/3OpSKgT",
    "https://amzn.to/45faMIq",
    "https://amzn.to/427vffL",
    "https://amzn.to/3VDnOv5",
    "https://amzn.to/3pfihPn",
    "https://amzn.to/3HEFSPJ",
    "https://amzn.to/3LYWCDT",
    "https://amzn.to/41b5oD9",
    "https://amzn.to/41a4G8U",
    "https://amzn.to/3M0UZ8s",
    "https://amzn.to/418owl8",
    "https://amzn.to/3LC2r8W",
    "https://amzn.to/3LAZnd2",
    "https://amzn.to/44vEQPM",
    "https://amzn.to/428qzad",
    "https://amzn.to/44vETeq",
    "https://amzn.to/3nyNYTc",
    "https://amzn.to/44uLVjv"
  ]