on:
  schedule:
    - cron: '0 11,13,16,19,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run script
        run: /usr/bin/python3 lista.py
